- name: Install EPEL Repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Enable RHEL optional RPMs
  ini_file:
    dest: /etc/yum.repos.d/redhat.repo
    section: rhel-7-server-optional-rpms
    option: enabled
    value: 1
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'
