# Path to the shared storage location on the head node
storage_path: /export

# IP address range and netmask of the compute nodes
compute_ip_range: "10.110.0.0/255.255.0.0"

# Mounts
mounts:
  apps:
    server: "{{ head_node }}"
    export: "{{ storage_path + '/apps' }}"
    mountpoint: /opt/apps
    export_opts: "{{ compute_ip_range }}(rw,no_root_squash,sync)"
    mount_opts: intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail
  data:
    server: "{{ head_node }}"
    export: "{{ storage_path + '/data' }}"
    mountpoint: /opt/data
    export_opts: "{{ compute_ip_range }}(rw,no_root_squash,sync)"
    mount_opts: intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail
  service:
    server: "{{ head_node }}"
    export: "{{ storage_path + '/service' }}"
    mountpoint: /opt/service
    export_opts: "{{ compute_ip_range }}(rw,no_root_squash,sync)"
    mount_opts: intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail
  site:
    server: "{{ head_node }}"
    export: "{{ storage_path + '/site' }}"
    mountpoint: /opt/site
    export_opts: "{{ compute_ip_range }}(rw,no_root_squash,sync)"
    mount_opts: intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail
  home:
    server: "{{ head_node }}"
    export: /home
    mountpoint: /home
    export_opts: "{{ compute_ip_range }}(rw,no_root_squash,sync)"
    mount_opts: intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail
